
timeout: 10

jwt_key: 7sMmCB6JYg59
web_bind_ip: 0.0.0.0
web_bind_port: 8083

sqlite_uri: sqlite:///data/RssSub.db

log_file: log/result.log
log_err_file: log/error.log

upload_file_ext: ['png', 'jpg', 'jpeg']
